### ISSUE TITLE
Error when running npm run test

### ISSUE THREAD

**Issue by xwizzell** [awslabs/aws-centralized-waf-and-vpc-security-group-management#7]
**Describe the bug**
I get the following error when running npm run test ?

**Screenshots**
See attached 

![npm_test_error](https://user-images.githubusercontent.com/35303690/95507168-a2f9c180-0976-11eb-8c90-f774279e1c7d.jpg)

**Comment by gsingh04** [comment]
Hello,

Thank you for reporting the issue. I was able to see the behavior at my end as well. This issue is because of mismatch in aws-lambda-event-sources version.

To resolve this please add following dependency in [package.json](https://github.com/awslabs/aws-centralized-waf-and-vpc-security-group-management/blob/239ccde16f116b55646538eee6ba9ae5109bfd16/source/resources/package.json#L23) and try again.
```
"@aws-cdk/aws-lambda-event-sources": "^1.49.1",
```
Additionally, please run ```npm run build``` before running test as the cdk unit tests look for lambda zips, and you would see following error if you run unit tests without building the lambda zips.
<img width="1030" alt="Screen Shot 2020-10-08 at 10 49 37 PM" src="https://user-images.githubusercontent.com/16402701/95536267-a150ed80-09b8-11eb-887a-e69de0d39231.png">

Let us know if this helps.

**Comment by maykays** [comment]
Please re-open if the issue persists.

**Comment by xwizzell** [comment]
Hello I'm still seeing the error even after adding the entry to the package.json 

![iQueue-error](https://user-images.githubusercontent.com/35303690/95766788-64ffe480-0c79-11eb-80bf-369e130fdd37.jpg)
![package-json](https://user-images.githubusercontent.com/35303690/95766794-67623e80-0c79-11eb-8fec-5fe80ce70f47.jpg)
