### ISSUE TITLE
Update dependencies - strategy

### ISSUE THREAD

**Issue by include** [awslabs/aws-centralized-waf-and-vpc-security-group-management#8]
Hi,

After cloning the repo, I follow the installation steps: 

```
npm i
npm run prettier-format
npm run lint
npm run build
cd source/resources
npm i
```
and this last npm install step I get.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: resources@1.0.0
npm ERR! Found: jest@25.5.4
npm ERR! node_modules/jest
npm ERR!   dev jest@"^25.5.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jest@"^26.6.3" from @aws-cdk/assert@1.94.1
npm ERR! node_modules/@aws-cdk/assert
npm ERR!   dev @aws-cdk/assert@"^1.56.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/fcabrita/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fcabrita/.npm/_logs/2021-03-17T12_19_14_543Z-debug.log
```

I noticed that in the root of the project and on this folder, there are many (very) outdated dependencies.

My two questions are:
- Help fixing this error above.
- What's the best strategy? Should I stick with your versions or should I update all deps prior to any npm i?

Thank you

Cheers,
F

**Comment by gsingh04** [comment]
Thanks @include for opening the issue,

The issue is arising because we did not pin the package versions in the package.json. We avoiding pinning versions so you can leverage newer versions of the dependencies.

In your case, this particular dependency seems to be causing the issue.  
```
npm ERR! Could not resolve dependency:
npm ERR! peer jest@"^26.6.3" from @aws-cdk/assert@1.94.1
```

I would recommend to update **jest** or any dependency that breaks the installation. Let us know, we will be here to look into this further if the issue persists even after updating the dependencies.
